name: Validate Prompts

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Validate prompt schema
      run: |
        python core/prompt_validator.py prompts/
        
    - name: Check JSON formatting
      run: |
        python -c "
        import json
        from pathlib import Path
        errors = []
        for f in Path('prompts').rglob('*.json'):
            try:
                with open(f) as file:
                    json.load(file)
            except Exception as e:
                errors.append(f'{f}: {e}')
        if errors:
            print('JSON formatting errors:')
            for e in errors:
                print(f'  - {e}')
            exit(1)
        print('✅ All JSON files are properly formatted')
        "
        
    - name: Generate validation report
      if: always()
      run: |
        echo "## Validation Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        python core/cli.py stats >> $GITHUB_STEP_SUMMARY
